import Head from "next/head";
import AutoAction from "@/components/AutoAction";
import NoBid from "@/components/NoBid";

const BuyBids = () => {
    return ( 
        <>
        <Head>
            <title>Buy Bid - Victorious bidders</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <section id="dashboard" className="h-full w-[90%] sm:w-full px-2 sm:px-10">
            <header className="h-20 w-full flex items-center justify-start">
                <h2 className="text-accent font-bold text-3xl">Buy Bid</h2>
            </header>
            <div className="w-fll h-max">
                <NoBid/>
            </div>
            <div className="">
                
            </div>
            <AutoAction/>
        </section>
        </>
     );
}
 
export default BuyBids;