import Bonus from "@/components/Bonus";
import History from "@/components/History";
import Head from "next/head";
import Link from "next/link";

export default function Home() {
  return (
    <>
      <Head>
        <title>Dashboard - Victorious bidders</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <section id="dashboard" className="h-full w-full px-2 sm:px-10">
          <header className="h-20 w-full flex items-center justify-start">
              <h2 className="text-accent font-bold text-3xl">Dashboard</h2>
          </header>
          <div className="w-full h-max py-8 rounded mb-4 bg-accent shadow-md flex items-center justify-center flex-col">
            <div className="h-max w-max">
              <i className="fa fa-warning text-center text-danger mr-1"></i>
              <span className="text-center text-danger">Risk Warning</span>
            </div>
            <p>Participate only with spare cash</p>
          </div>
          <div className="-full h-max py-3 rounded mb-4 bg-accent shadow-md flex items-center justify-start px-3">
            <p className="mr-10 text-accent2 text-base">No coin available at the moment, Come back later.</p>
            <Link href="/" className="py-2 px-3 text-accent rounded bg-neutralDark">Auction Forum</Link>
          </div>
          <div className="h-max w-full flex items-center justify-between py-3">
            <div className="h-[200px] w-[48%] rounded bg-accent p-10">
              <p className="text-base text-offBlack mb-2">Locked Vault</p>
              <h2 className="text-2xl font-bold text-offBlack">₦300,000</h2>
            </div>
            <div className="h-[200px] w-[48%] rounded bg-accent p-10">
              <p className="text-base text-offBlack mb-2">Sellable Vault</p>
              <h2 className="text-2xl font-bold text-offBlack mb-3">₦5,000</h2>
              <Link href={"/"} className="py-2 px-3 text-accent rounded bg-neutralDark mt-10">Sell</Link>
            </div>
          </div>
          <Bonus/>
          <div className="my-10">
            <h2 className="text-xl font-bold mb-4 text-accent">All Transactions</h2>
            <History />
          </div>
      </section>
    </>
  );
}
