import Head from "next/head";
import Link from "next/link"; 
import AutoAction from "@/components/AutoAction";
import NoBid from "@/components/NoBid";

const Lobby = () => {
    return ( 
        <>
        <Head>
            <title>Auction Forum - Victorious bidders</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <section id="dashboard" className="h-full w-full px-2 sm:px-10">
            <header className="h-20 w-full flex items-center justify-start">
                <h2 className="text-accent font-bold text-3xl">Auction Forum</h2>
            </header>
            <div className="h-max w-full flex flex-col sm:flex-row justify-between items-start py-3">
                <div className="p-3 bg-accent min-h-max mb-2 sm:mb-0 sm:min-h-[250px] w-full sm:w-[48%] rounded">
                    <NoBid/>
                </div>
                <div className="p-3 bg-accent min-h-max sm:min-h-[250px] w-full sm:w-[48%] rounded">
                    <form action="/" className="h-max w-full">
                        <h2 className="text-xl text-offBlack">Request Entry</h2>
                        <div id="error" className="text-danger text-sm my-2">Please request entry</div>
                        <div className="h-max w-full mb-4">
                            <div className="h-max w-full">
                                <label htmlFor="amount" className="text-base text-offBlack font-semibold">Amount</label>
                                <input type="text" id="amount" placeholder="Amount" className="p-2 h-10 w-full border border-grey rounded outline-none" />
                                <div className="text-end w-full h-max text-sm text-grey">Max. bid: ₦500,000</div>
                            </div>
                            <div className="h-max w-full">
                                <label htmlFor="durations" className="text-base text-offBlack font-semibold">Duration</label>
                                <select name="duration" id="duration" className="p-2 h-10 w-full border border-grey rounded outline-none">
                                    <option value="">-- Select a Package --</option>
                                    <option value="">7 days - 100% profit</option>
                                </select>
                            </div>
                        </div>
                        <div className="w-full h-max flex items-center mb-2">
                            <p className="text-sm text-grey">Auto Action <span><i className="fa fa-rocket text-green-500"></i></span></p>
                            <p className="text-sm text-grey ml-1">0 slots available</p>
                        </div>
                        <div className="w-full h-max flex items-center  mb-3">
                            <button className="h-[20px] w-[40px] bg-grey rounded-full p-[5px] mr-1">
                                <div className="h-[10px] w-[10px] rounded-full bg-accent"></div>
                            </button>
                            <p>Off (<span className="text-danger text-sm">Auto auction unavailable</span>)</p>
                        </div>
                        <p className="text-sm text-grey">Let the system auction for you automatically during auction time for a fee of 20% of your bid amount <Link className="text-accent2 underline" href={"/"}>Learn More</Link></p>
                        <div className="w-full h-max flex items-center justify-center mt-10">
                            <button type="submit" className="py-2 px-10 bg-green-500 rounded opacity-70 hover:opacity-100 transition-all duration-300 text-accent text-base">Submit</button>
                        </div>
                    </form>
                    <AutoAction/>
                </div>
            </div>
        </section>
        </>
     );
}
 
export default Lobby;