import Bonus from "@/components/Bonus";
import History from "@/components/History";
import Head from "next/head";

const Trasactions = () => {
    return ( 
        <>
        <Head>
            <title>Sell Bid - Victorious bidders</title>
            <meta name="description" content="Generated by create next app" />
            <meta name="viewport" content="width=device-width, initial-scale=1" />
            <link rel="icon" href="/favicon.ico" />
        </Head>
        <section id="dashboard" className="h-full w-full px-2 sm:px-10">
            <header className="h-20 w-full flex items-center justify-start">
                <h2 className="text-accent font-bold text-3xl">Transactions</h2>
            </header>
            <Bonus/>
            <History/>
        </section>
        </>
     );
}
 
export default Trasactions;